server:
  port: 80

spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
        - id: userprofile-service
          uri: http://localhost:9093
          predicates:
            - Path=/userprofile/**

      default-filters:
        - RewritePath= /(?<segment>.*) , /api/v1/$\{segment}